theme = "dracula"

[keys.insert]
C-s = ":w"

[editor]
color-modes = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.indent-guides]
render = true
skip-levels = 1
