[[binaries]]
name = "nu"
repo = "nushell/nushell"
exe = "nu"
version_arg = "--version"

[[binaries]]
name = "uv"
repo = "astral-sh/uv"
exe = "uv"
version_arg = "--version"

[[binaries]]
name = "zoxide"
repo = "ajeetdsouza/zoxide"
exe = "zoxide"
version_arg = "--version"

[[binaries]]
name = "jj"
repo = "jj-vcs/jj"
exe = "jj"
version_arg = "--version"

[[binaries]]
name = "fzf"
repo = "junegunn/fzf"
exe = "fzf"
version_arg = "--version"

[[binaries]]
name = "gh"
repo = "cli/cli"
exe = "gh"
version_arg = "--version"

[[binaries]]
name = "yazi"
repo = "sxyazi/yazi"
exe = "yazi"
version_arg = "--version"

[[binaries]]
name = "micro"
repo = "zyedidia/micro"
exe = "micro"
version_arg = "--version"

[[binaries]]
name = "lazygit"
repo = "jesseduffield/lazygit"
exe = "lazygit"
version_arg = "--version"

[[binaries]]
name = "eza"
repo = "eza-community/eza"
exe = "eza"
version_arg = "--version"

[[binaries]]
name = "bat"
repo = "sharkdp/bat"
exe = "bat"
version_arg = "--version"

[[binaries]]
name = "rclone"
repo = "rclone/rclone"
exe = "rclone"
version_arg = "--version"
